CREATE TABLE user (
    USER_NO int primary key auto_increment,
    UNAME varchar(20) not null,
    PASS varchar(256) not null,
    UNIQUE (PASS)
);

CREATE TABLE CATEGORY (
    CID CHAR(4) PRIMARY KEY,
    CNAME VARCHAR(20) not null,
    CDESC VARCHAR(256) not null
);

CREATE TABLE STEP (
    CID CHAR(4),
    SNO CHAR(4),
    PRIMARY KEY (CID,SNO),
    FOREIGN KEY (CID) REFERENCES CATEGORY(CID)
);

CREATE TABLE STEP_DETAIL (
    CID CHAR(4),
    SNO CHAR(4),
    DNO CHAR(4),
    DETAIL VARCHAR(256) not null,
    PRIMARY KEY (CID,SNO,DNO),
    FOREIGN KEY (CID) REFERENCES CATEGORY(CID)
);

CREATE TABLE ACHIEVEMENT (
    CID CHAR(4),
    SNO CHAR(4),
    DNO CHAR(4),
    USER_NO int,
    ACHIEVE BOOL DEFAULT(0),
    PRIMARY KEY (CID,SNO,DNO,USER_NO),
    FOREIGN KEY (CID) REFERENCES CATEGORY(CID),
    FOREIGN KEY (USER_NO) REFERENCES USER(USER_NO)
);

CREATE DATABASE life_step;

CREATE USER 'dbuser'@'localhost' IDENTIFIED BY 'ecc';

GRANT ALL ON life_step.* 'dbuser'@'localhost';

